vlovgr/ciris

build.sbt
docs/src/main/tut/index.md
modules/core/shared/src/main/scala/ciris/ConfigError.scala
modules/core/shared/src/main/scala/ciris/ConfigReader.scala
modules/core/shared/src/test/scala/ciris/ConfigErrorsSpec.scala
modules/core/shared/src/test/scala/ciris/PropertySpec.scala
modules/enumeratum/shared/src/test/scala/ciris/enumeratum/readers/EnumeratumConfigReadersSpec.scala
modules/generic/jvm/src/main/scala/ciris/generic/package.scala
modules/generic/jvm/src/main/scala/ciris/generic/readers/GenericConfigReaders.scala
modules/generic/jvm/src/test/scala/ciris/generic/readers/GenericConfigReadersSpec.scala

Support for loading shapeless' coproducts and products with arity 1 (including value classes).

Add ciris-generic module using shapeless

---

modules/core/js/src/main/scala/ciris/readers/ConfigReaders.scala
modules/core/jvm/src/main/scala/ciris/readers/ConfigReaders.scala
modules/core/jvm/src/main/scala/ciris/readers/JavaIoConfigReaders.scala
modules/core/jvm/src/main/scala/ciris/readers/JavaNetConfigReaders.scala
modules/core/jvm/src/main/scala/ciris/readers/JavaNioFileConfigReaders.scala
modules/core/jvm/src/test/scala/ciris/readers/JavaIoConfigReadersSpec.scala
modules/core/jvm/src/test/scala/ciris/readers/JavaNetConfigReadersSpec.scala
modules/core/jvm/src/test/scala/ciris/readers/JavaNioCharsetConfigReadersJvmSpec.scala
modules/core/jvm/src/test/scala/ciris/readers/JavaNioFileConfigReadersSpec.scala
modules/core/shared/src/main/scala/ciris/readers/JavaNioCharsetConfigReaders.scala
modules/core/shared/src/main/scala/ciris/readers/JavaUtilConfigReaders.scala
modules/core/shared/src/main/scala/ciris/readers/PrimitiveConfigReaders.scala
modules/core/shared/src/test/scala/ciris/readers/JavaNioCharsetConfigReadersSpec.scala
modules/core/shared/src/test/scala/ciris/readers/JavaUtilConfigReadersSpec.scala
modules/core/shared/src/test/scala/ciris/readers/PrimitiveConfigReadersSpec.scala

Add support for reading:
- `Double` and `Float` percent format (i.e. `57%` becomes `0.57`)
- `java.io.File`
- `java.net.InetAddress`
- `java.nio.charset.Charset`
- `java.nio.file.Path`
- `java.util.regex.Pattern`

Add support for reading more types

---

build.sbt
modules/squants/shared/src/main/scala/ciris/squants/readers/SquantsConfigReaders.scala
tests/shared/src/test/scala/ciris/squants/readers/SquantsConfigReadersSpec.scala

Add support for reading `MomentOfInertia`, `AngularAcceleration`, and `Torque`. ([#227](https://github.com/typelevel/squants/pull/227))

Upgrade squants to 1.3.0

---

docs/src/main/tut/docs/sources/readme.md
docs/src/main/tut/docs/validation/readme.md
modules/core/shared/src/main/scala/ciris/ConfigSource.scala

To support use cases related to custom configuration sources.

Make ConfigSource not sealed

---

docs/src/main/resources/microsite/css/custom.css
docs/src/main/resources/microsite/data/menu.yml
docs/src/main/tut/docs/basics/readme.md
docs/src/main/tut/docs/concepts/readme.md
docs/src/main/tut/docs/environments/readme.md
docs/src/main/tut/docs/modules/readme.md
docs/src/main/tut/docs/readers/readme.md
docs/src/main/tut/docs/sources/readme.md
docs/src/main/tut/docs/validation/readme.md
docs/src/main/tut/index.md
modules/core/shared/src/main/scala/ciris/ConfigValue.scala
tests/shared/src/test/scala/ciris/ConfigValueSpec.scala
tests/shared/src/test/scala/ciris/PropertySpec.scala

- Add `Core Concepts` and `Modules Overview` sections to usage guide.
- Change headings in the documentation to be hyperlinks with anchors.
- Change links in the usage guide to be underlined when hovered.
Also use `text-decoration-skip: ink;` throughout microsite.
- The `ConfigValue` class now has a sensible `toString` method.

Add Core Concepts and Modules Overview sections to usage guide

---

modules/refined/js/src/main/scala/ciris/refined/readers/RefinedConfigReaders.scala
modules/refined/jvm/src/main/scala/ciris/refined/readers/RefinedConfigReaders.scala

The `ciris-refined` module now uses a `WeakTypeTag` on the JVM (still a `ClassTag` on Scala.js).

Use WeakTypeTag for refined on JVM

---

docs/src/main/tut/docs/concepts/readme.md
docs/src/main/tut/docs/modules/readme.md
docs/src/main/tut/docs/readers/readme.md
docs/src/main/tut/docs/sources/readme.md
modules/core/shared/src/main/scala/ciris/ConfigError.scala
modules/core/shared/src/main/scala/ciris/ConfigKeyType.scala
modules/core/shared/src/main/scala/ciris/ConfigReader.scala
modules/core/shared/src/main/scala/ciris/ConfigSource.scala
modules/core/shared/src/main/scala/ciris/ConfigSourceEntry.scala
modules/core/shared/src/main/scala/ciris/ConfigValue.scala
modules/core/shared/src/main/scala/ciris/ConfigValuePartiallyApplied.scala
modules/core/shared/src/main/scala/ciris/package.scala
modules/core/shared/src/main/scala/ciris/readers/DerivedConfigReaders.scala
modules/core/shared/src/main/scala/ciris/readers/PrimitiveConfigReaders.scala
modules/enumeratum/shared/src/main/scala/ciris/enumeratum/readers/EnumeratumConfigReaders.scala
modules/generic/shared/src/main/scala/ciris/generic/readers/GenericConfigReaders.scala
project/SourceGenerators.scala
tests/shared/src/test/scala/ciris/CirisSpec.scala
tests/shared/src/test/scala/ciris/ConfigSourceSpec.scala
tests/shared/src/test/scala/ciris/LoadConfigsSpec.scala
tests/shared/src/test/scala/ciris/PropertySpec.scala

* Configuration sources can now be created for different key types.
* Sources and readers are now separated with `ConfigSourceEntry`.
* Add `arg` method for reading command-line arguments by index.
**Miscellaneous**:
* Add `ConfigKeyType#Argument`.
* Rename `ConfigReader#fold` to `mapBoth`.
* Add `ConfigReader#map` and `ConfigSource#byIndex`.
* Fix creating some unnecessary `ConfigSource` instances.
* Remove `ConfigReader#pure` since it can no longer work.
* Add `ConfigValuePartiallyApplied` to support the `read` method.

Add support for different key types

---

.travis.yml
build.sbt
docs/src/main/tut/docs/modules/readme.md
modules/core/shared/src/main/scala/ciris/ConfigReader.scala

All project documentation (usage guide and API documentation) is now compiled and tested against all `crossScalaVersions`. This required very minor changes in the documentation, except for a few cases of shapeless examples which require macro paradise on 2.10.6. With macro paradise included, the shapeless examples work fine, but refined's auto macro seems to have problems.
```
[tut] *** Error reported at /Users/vlovgr/Projects/ciris/docs/src/main/tut/docs/environments/readme.md:69
// <console>:44: error: exception during macro expansion:
// java.lang.ClassCastException: eu.timepit.refined.BooleanValidate$$anon$2 cannot be cast to eu.timepit.refined.api.Validate
// 	at eu.timepit.refined.macros.RefineMacro.impl(RefineMacro.scala:23)
// 	at …
```

Make sure docs test/compile on cross versions

---

modules/core/shared/src/main/scala/ciris/ConfigErrors.scala
modules/core/shared/src/main/scala/ciris/ConfigException.scala
modules/core/shared/src/main/scala/ciris/syntax.scala
tests/shared/src/test/scala/ciris/CirisSyntaxSpec.scala
tests/shared/src/test/scala/ciris/ConfigErrorsSpec.scala
tests/shared/src/test/scala/ciris/ConfigExceptionSpec.scala
tests/shared/src/test/scala/ciris/PropertySpec.scala

- Add `ConfigException` throwable, wrapping `ConfigErrors`.
- Add `ConfigErrors#toException` for converting to `ConfigException`.
- Add `Either[ConfigErrors, T]#orThrow()` syntax in the `syntax` package.
This allows for a convenient way to have failed configuration loading halt program execution - typically during application startup.
```
scala> import ciris._, ciris.syntax._
import ciris._
import ciris.syntax._
scala> loadConfig(env[String]("HOME"))(identity).orThrow()
res0: String = /Users/vlovgr
scala> loadConfig(env[String]("API_KEY"))(identity).orThrow()
ciris.ConfigException: configuration loading failed with the following error.
- Missing environment variable [API_KEY].
at ciris.ConfigException$.apply(ConfigException.scala:50)
at …
```

Add ConfigException and orThrow syntax

---

build.sbt
docs/src/main/tut/docs/modules/readme.md
docs/src/main/tut/index.md
modules/core/shared/src/main/scala/ciris/ConfigReader.scala
modules/core/shared/src/main/scala/ciris/ConfigSource.scala
modules/spire/shared/src/main/scala/ciris/spire/package.scala
modules/spire/shared/src/main/scala/ciris/spire/readers/SpireConfigReaders.scala
tests/shared/src/test/scala/ciris/ConfigReaderSpec.scala
tests/shared/src/test/scala/ciris/ConfigSourceSpec.scala
tests/shared/src/test/scala/ciris/spire/readers/SpireConfigReadersSpec.scala

Add a `ciris-spire` module with support for [spire](https://github.com/non/spire) number types: `Algebraic`, `Interval[Rational]`, `Natural`, `Number`, `Polynomial[Rational]`, `Rational`, `Real`, `SafeLong`, `Trilean`, `UByte`, `UInt`, `ULong`, and `UShort`.
Bonus:
- Add `ConfigReader#collect`, `mapTry`, `mapCatchNonFatal`, `fromTryOption`.
- Add `ConfigSource#fromEntries`.
- Update Ammonite to 1.0.2.

Add spire module

---

modules/core/shared/src/main/scala/ciris/ConfigError.scala
modules/core/shared/src/main/scala/ciris/ConfigValue.scala
tests/shared/src/test/scala/ciris/ConfigValueSpec.scala

Add `ConfigValue#orElse` for chaining `ConfigValue`s, allowing to specify alternative values in case the previous ones are not available.
```scala
import ciris._
val awsSecretAccessKey =
env[String]("AWS_SECRET_ACCESS_KEY").
orElse(env[String]("AWS_SECRET_KEY"))
// awsSecretAccessKey: ConfigValue[String] = ConfigValue(Left(Combined(Vector(MissingKey(AWS_SECRET_ACCESS_KEY, Environment), MissingKey(AWS_SECRET_KEY, Environment)))))
awsSecretAccessKey.value.left.map(_.message)
// res0: Either[String,String] = Left(Missing environment variable [AWS_SECRET_ACCESS_KEY], Missing environment variable [AWS_SECRET_KEY])
```

Add ConfigValue#orElse

---

modules/core/shared/src/main/scala/ciris/ConfigValue.scala
modules/refined/shared/src/main/scala/ciris/refined/syntax.scala
tests/shared/src/test/scala/ciris/ConfigValueSpec.scala
tests/shared/src/test/scala/ciris/refined/RefinedConfigValueSyntaxSpec.scala

Allows to refine configuration values with `refine` and `mapRefine`, like in the following examples.
```scala
scala> import ciris._, ciris.refined.syntax._, eu.timepit.refined.api.Refined, eu.timepit.refined.collection.NonEmpty
import ciris._
import ciris.refined.syntax._
import eu.timepit.refined.api.Refined
import eu.timepit.refined.collection.NonEmpty
scala> val secret = ConfigValue(Right("secret")).refine[NonEmpty]
secret: ConfigValue[Refined[String,NonEmpty]] = ConfigValue(Right(secret))
```
```scala
scala> import ciris._, ciris.refined.syntax._, eu.timepit.refined.api.Refined, eu.timepit.refined.string.Uri
import ciris._
import ciris.refined.syntax._
import eu.timepit.refined.api.Refined
import eu.timepit.refined.string.Uri
scala> val host = ConfigValue(Right("google.com"))
host: …
```

Add ConfigValue#refine and mapRefine syntax

---

.jvmopts

Inspired by [cats](https://github.com/typelevel/cats/blob/master/.jvmopts), but also adds `-Xss6M`.

Add jvmopts for default java options

---

modules/core/shared/src/main/scala/ciris/ConfigException.scala
tests/shared/src/test/scala/ciris/ConfigExceptionSpec.scala

Ensures that the exception message is included in `toString`, and therefore also in stack traces.
```
scala> loadConfig(env[Int]("A"), prop[Int]("B"))(_ + _).orThrow()
ciris.ConfigException: configuration loading failed with the following errors.
- Environment variable [A] with value [x] cannot be converted to type [Int]: java.lang.NumberFormatException: For input string: "x".
- Missing system property [B].
at ciris.ConfigException$.apply(ConfigException.scala:46)
at ciris.ConfigErrors$.toException$extension(ConfigErrors.scala:109)
at ciris.syntax$EitherConfigErrorsSyntax$.$anonfun$orThrow$1(syntax.scala:22)
at ciris.syntax$EitherConfigErrorsSyntax$.$anonfun$orThrow$1$adapted(syntax.scala:22)
at scala.util.Either.fold(Either.scala:189)
at …
```

Fix ConfigException#toString

---

modules/core/js/src/main/scala/ciris/CirisPlatformSpecific.scala
modules/core/js/src/main/scala/ciris/ConfigKeyTypePlatformSpecific.scala
modules/core/js/src/main/scala/ciris/ConfigSourcePlatformSpecific.scala
modules/core/jvm/src/main/scala/ciris/CirisPlatformSpecific.scala
modules/core/jvm/src/main/scala/ciris/ConfigKeyTypePlatformSpecific.scala
modules/core/jvm/src/main/scala/ciris/ConfigSourcePlatformSpecific.scala
modules/core/shared/src/main/scala/ciris/ConfigKeyType.scala
modules/core/shared/src/main/scala/ciris/ConfigReader.scala
modules/core/shared/src/main/scala/ciris/ConfigSource.scala
modules/core/shared/src/main/scala/ciris/ConfigSourceEntry.scala
modules/core/shared/src/main/scala/ciris/package.scala
tests/jvm/src/test/scala/ciris/CirisPlatformSpecificSpec.scala
tests/jvm/src/test/scala/ciris/ConfigSourcePlatformSpecificSpec.scala
tests/jvm/src/test/scala/ciris/JvmPropertySpec.scala
tests/shared/src/test/scala/ciris/ConfigReaderSpec.scala
tests/shared/src/test/scala/ciris/ConfigSourceEntrySpec.scala

Add `file` and `fileWithName` methods for reading the contents of files, optionally modifying the read file contents before attempting the type conversion, and optionally specifying a charset. Note that this is currently only implemented for the JVM. Also adds the following in support of the functionality: `ConfigKeyType#File`, `ConfigSource#File`, `ConfigReader#mapEntryValue`,  `ConfigSourceEntry#mapValue`.
```
❯ cat /tmp/num.txt
3
```
```
scala> import ciris._
import ciris._
scala> fileWithName[Int]("/tmp/num.txt")
res0: ciris.ConfigValue[Int] =
ConfigValue(Left(WrongType((/tmp/num.txt,UTF-8), 3
, Int, ConfigKeyType(file), Some(java.lang.NumberFormatException: For input string: "3
"))))
scala> fileWithName[Int]("/tmp/num.txt", _.trim)
res1: ciris.ConfigValue[Int] = ConfigValue(Right(3)) …
```

Add support for reading files

---

latestVersion.sbt
modules/core/js/src/main/scala/ciris/readers/ConfigReaders.scala
modules/core/jvm/src/main/scala/ciris/readers/ConfigReaders.scala
modules/core/shared/src/main/scala/ciris/Secret.scala
modules/core/shared/src/main/scala/ciris/readers/CirisConfigReaders.scala
tests/shared/src/test/scala/ciris/SecretSpec.scala
version.sbt

Introduces `Secret[A]` which can wrap values to avoid secret configuration values in log output.
```scala
scala> import ciris._, ciris.refined._, eu.timepit.refined.types.string._
import ciris._
import ciris.refined._
import eu.timepit.refined.types.string._
scala> env[Secret[NonEmptyString]]("DATABASE_PASSWORD")
res0: ciris.ConfigValue[ciris.Secret[eu.timepit.refined.types.string.NonEmptyString]] = ConfigValue(Right(Secret(***)))
```

Add Secret class to avoid logging secrets

---

docs/src/main/tut/index.md
readme.md

Backwards binary compatibility for the library is guaranteed between minor versions.  
For example, `0.6.x` is backwards binary compatible with `0.6.y` for any `x > y`.  
More recent minor versions are drop-in replacements for earlier minor versions.

Clarify compatibility rules

---

docs/src/main/tut/docs/concepts/readme.md
modules/core/jvm/src/main/scala/ciris/ConfigSourcePlatformSpecific.scala
modules/core/native/src/main/scala/ciris/ConfigSourcePlatformSpecific.scala
modules/core/shared/src/main/scala/ciris/ConfigEntry.scala
modules/core/shared/src/main/scala/ciris/ConfigReader.scala
modules/core/shared/src/main/scala/ciris/ConfigSource.scala
modules/core/shared/src/main/scala/ciris/readers/DerivedConfigReaders.scala
modules/enumeratum/shared/src/main/scala/ciris/enumeratum/readers/EnumeratumConfigReaders.scala
modules/generic/shared/src/main/scala/ciris/generic/readers/GenericConfigReaders.scala
tests/shared/src/test/scala/ciris/ConfigEntrySpec.scala
tests/shared/src/test/scala/ciris/PropertySpec.scala

This is in preparation of unifying `ConfigValue` and `ConfigSourceEntry` into `ConfigEntry`.

Rename ConfigSourceEntry to ConfigEntry

---

modules/core/jvm/src/main/scala/ciris/ConfigSourcePlatformSpecific.scala
modules/core/native/src/main/scala/ciris/ConfigSourcePlatformSpecific.scala
modules/core/shared/src/main/scala/ciris/ConfigEntry.scala
modules/core/shared/src/main/scala/ciris/ConfigReader.scala
modules/core/shared/src/main/scala/ciris/ConfigSource.scala
modules/core/shared/src/main/scala/ciris/ConfigValue.scala
modules/core/shared/src/main/scala/ciris/readers/DerivedConfigReaders.scala
modules/enumeratum/shared/src/main/scala/ciris/enumeratum/readers/EnumeratumConfigReaders.scala
modules/generic/shared/src/main/scala/ciris/generic/readers/GenericConfigReaders.scala
tests/shared/src/test/scala/ciris/ConfigEntrySpec.scala
tests/shared/src/test/scala/ciris/PropertySpec.scala

- Change `ConfigEntry` to include the original unmodified source value.
`ConfigEntry[K, V]` has been changed to `ConfigEntry[K, S, V]`.
- Change `ConfigEntry` to be a `final class` with `private` constructor.
Use the `ConfigEntry#apply` method to create instances of `ConfigEntry`.
- Rename the previous `ConfigEntry#mapValue[A]` to `mapValueRight[A]`.
- Add `ConfigEntry#mapValue[A]` for `Either[ConfigError, V] => Either[ConfigError, A]`.
- Change `ConfigSouce#toString` to include both the source value and the value if they are different.

Add ConfigEntry#sourceValue

---

.travis.yml
build.sbt
docs/src/main/tut/docs/contributing/readme.md
docs/src/main/tut/docs/modules/readme.md
modules/generic/shared/src/main/scala/ciris/generic/decoders/GenericConfigDecoders.scala
tests/shared/src/test/scala/ciris/generic/decoders/GenericConfigDecodersSpec.scala

With `ConfigSource` and `ConfigDecoder` being more generic, we can now support products of arbitrary arity with `ciris-generic`.

Change to support arbitrary arity products

---

build.sbt
docs/src/main/tut/index.md
latestVersion.sbt
modules/cats-effect/shared/src/main/scala/ciris/cats/effect/api/CatsEffectInstancesForCiris.scala
modules/cats-effect/shared/src/main/scala/ciris/cats/effect/package.scala
modules/cats/shared/src/main/scala/ciris/cats/api/CatsInstancesForCiris.scala
modules/core/jvm/src/main/scala/ciris/CirisPlatformSpecific.scala
modules/core/native/src/main/scala/ciris/CirisPlatformSpecific.scala
modules/core/shared/src/main/scala/ciris/ConfigSource.scala
modules/core/shared/src/main/scala/ciris/api/ApplicativeError.scala
modules/core/shared/src/main/scala/ciris/api/MonadError.scala
modules/core/shared/src/main/scala/ciris/api/Sync.scala
modules/core/shared/src/main/scala/ciris/package.scala
tests/jvm/src/test/scala/ciris/CirisPlatformSpecificSpec.scala
tests/jvm/src/test/scala/ciris/JvmPropertySpec.scala
tests/jvm/src/test/scala/ciris/cats/api/CatsInstancesForCirisJvmSpec.scala
tests/shared/src/test/scala/ciris/CirisSpec.scala
tests/shared/src/test/scala/ciris/ConfigSourceSpec.scala
tests/shared/src/test/scala/ciris/cats/api/CatsInstancesForCirisSpec.scala
tests/shared/src/test/scala/ciris/cats/effect/api/CatsEffectInstancesForCirisSpec.scala

- Add simplified `ApplicativeError`, `MonadError`, and `Sync` from cats and cats-effect.
- Add `ciris-cats-effect` module with conversions from `cats.effect.Sync` to ciris.
- Add `ConfigSource#transformF` for creating a new `ConfigSource` with new context `F[_]`.
- Add `ConfigSource#suspendF` for creating a new `ConfigSource` where reading is suspended into a new context `F[_]: Sync`.
- Add `argF`, `propF`, `fileSync`, and `fileWithNameSync` as pure alternatives, suspending reading into context `F[_]: Sync`.
- Add `envF` for lifting values into `F[_] : Applicative`.

Cats effect module

---

build.sbt
modules/cats-effect/shared/src/main/scala/ciris/cats/effect/api/CatsEffectInstancesForCiris.scala
tests/shared/src/test/scala/ciris/cats/effect/api/CatsEffectInstancesForCirisSpec.scala

Fix ambiguous implicits between `ciris-cats` and `ciris-cats-effect`.
- Change so that `ciris-cats-effect` depends on `ciris-cats`.
- Change so that `CatsEffectInstancesForCiris` extends `CatsInstancesForCiris `.

Fix cats and cats-effect ambiguous implicits

---

latestVersion.sbt
modules/core/js/src/main/scala/ciris/decoders/ConfigDecoders.scala
modules/core/jvm/src/main/scala/ciris/decoders/ConfigDecoders.scala
modules/core/native/src/main/scala/ciris/decoders/ConfigDecoders.scala
modules/core/shared/src/main/scala/ciris/decoders/MathConfigDecoders.scala
modules/core/shared/src/main/scala/ciris/decoders/PrimitiveConfigDecoders.scala
modules/core/shared/src/main/scala/ciris/decoders/ScalaUtilConfigDecoders.scala
tests/shared/src/test/scala/ciris/decoders/MathConfigDecodersSpec.scala
tests/shared/src/test/scala/ciris/decoders/PrimitiveConfigDecodersSpec.scala
tests/shared/src/test/scala/ciris/decoders/ScalaUtilConfigDecodersSpec.scala
version.sbt

- Add `ConfigDecoder[String, Regex]`.
- Add support for `yes/no` and `on/off` to `ConfigDecoder[String, Boolean]`.
- Workaround loss of precision for `ConfigDecoder[String, BigDecimal]` on Scala 2.10.

ConfigDecoder additions and fixes

---

docs/src/main/tut/docs/basics.md
modules/core/shared/src/main/scala/ciris/ConfigError.scala
modules/core/shared/src/main/scala/ciris/ConfigValue.scala
tests/shared/src/test/scala/ciris/ConfigErrorSpec.scala
tests/shared/src/test/scala/ciris/ConfigValueSpec.scala

- Add `ConfigError#isMissingKey` for checking whether an error occurred because the key was missing from the `ConfigSource` (for combined errors, whether all errors are due to missing keys).
- Change `ConfigValue#orElse` and `orNone` to only use the alternative value (or `None`) if the error is because of missing keys, as determined by `ConfigError#isMissingKey`.
For example, previously, a type conversion error for `PORT` in the following example:
```
> echo $PORT
changeme
scala> env[Int]("PORT").
|   orElse(prop[Int]("port").
|   orNone
res0: ConfigValue[Id, Option[Int]] = ConfigValue(Right(None))
```
would result in using the fallback values. This is probably not what you would expect, and this pull request changes `orElse` and `orNone` to only use fallback values if all previous errors …

Change orElse and orNone to work on missing keys

---

docs/src/main/tut/docs/basics.md
docs/src/main/tut/docs/supporting-new-sources.md
modules/core/shared/src/main/scala/ciris/decoders/DerivedConfigDecoders.scala
tests/shared/src/test/scala/ciris/decoders/DerivedConfigDecodersSpec.scala

Similarly to #124, this pull request changes the decoder for `Option[A]` to work on missing keys. Previously, the decoder would return `None` for other errors as well. For example, if there was an exception while reading the key, or if the key was set but we were unable to convert it.
```
❯ echo $NUM
changeme
scala> env[Option[Int]]("NUM").value
res0: Id[Either[ConfigError, Option[Int]]] = Right(None)
```
With the changes in this pull request, we now only return `None` when keys are missing.
```
scala> env[Option[Int]]("NUM").value
res0: Id[Either[ConfigError, Option[Int]]] = Left(WrongType(NUM, Environment, Right(changeme), changeme, Int, java.lang.NumberFormatException: For input string: "changeme"))
```

Change Option decoder to work on missing keys

---

build.sbt
docs/src/main/tut/docs/generic-module.md
scripts/try.sh
scripts/try.typelevel.sh

- Remove `ciris-generic` default import from try script to avoid overriding default behaviours.
- Add note to usage guide clarifying `ciris-generic` potentially overriding other behaviours.

Remove ciris-generic default import from try script

---

docs/src/main/tut/docs/basics.md
docs/src/main/tut/docs/environments.md
docs/src/main/tut/docs/supporting-new-sources.md
docs/src/main/tut/docs/validation.md
modules/core/shared/src/main/scala/ciris/ConfigValue.scala
tests/shared/src/test/scala/ciris/ConfigValueSpec.scala

This pull request removes the `A >: V` type parameter on `ConfigValue#orElse`. The benefit of removing it is that we no longer have to repeat ourselves by specifying the type to decode in the `orElse` argument, since the type can now be properly inferred.
```
scala> env[String]("API_KEY").
|   orElse(prop("api.key")).
|   orNone
res0: ConfigValue[Id, Option[String]] = ConfigValue(Right(None))
```
This includes also being able to infer the context type.
```
scala> envF[IO, String]("API_KEY").
|   orElse(propF("api.key")).
|   orNone
res0: ConfigValue[IO, Option[String]] = ConfigValue(<function1>)
```

Remove the ConfigValue#orElse type parameter

---

build.sbt
docs/src/main/tut/docs/supporting-new-sources.md
latestVersion.sbt
modules/cats-effect/shared/src/main/scala/ciris/cats/effect/syntax.scala
tests/shared/src/test/scala/ciris/cats/effect/CatsEffectSyntaxSpec.scala
version.sbt

The `suspendMemoizeF` function was previously not capturing the memoization effect.

Fix suspendMemoizeF

---

docs/src/main/tut/docs/basics.md
docs/src/main/tut/docs/logging.md
modules/cats/shared/src/main/scala/ciris/cats/api/CirisInstancesForCats.scala
modules/core/jvm/src/main/scala/ciris/CirisPlatformSpecific.scala
modules/core/shared/src/main/scala/ciris/ConfigDecoder.scala
modules/core/shared/src/main/scala/ciris/ConfigEntry.scala
modules/core/shared/src/main/scala/ciris/ConfigError.scala
modules/core/shared/src/main/scala/ciris/ConfigSource.scala
modules/core/shared/src/main/scala/ciris/ConfigValue.scala
modules/core/shared/src/main/scala/ciris/decoders/CirisConfigDecoders.scala
modules/core/shared/src/main/scala/ciris/package.scala
modules/refined/jvm/src/main/scala/ciris/refined/syntax.scala
tests/shared/src/test/scala/ciris/ConfigDecoderSpec.scala
tests/shared/src/test/scala/ciris/ConfigEntrySpec.scala
tests/shared/src/test/scala/ciris/ConfigErrorSpec.scala
tests/shared/src/test/scala/ciris/ConfigValueSpec.scala
tests/shared/src/test/scala/ciris/cats/api/CirisInstancesForCatsSpec.scala
tests/shared/src/test/scala/ciris/decoders/CirisConfigDecodersSpec.scala

**Hiding sensitive details**
- Change `ConfigValue#toString` and `ConfigEntry#toString` to not include values.
- Change `Show` instances for `ConfigValue` and `ConfigEntry` to not include values.
- Add `ConfigValue#toStringWithValue` and `ConfigEntry#toStringWithValues` for keeping the previous `toString` behaviours.
You'll no longer have to worry about accidentally logging values, unless you're explicitly logging the result from a function with `value` in the name (`sourceValue`, `value`, `toStringWithValue`, ...).
**Redacting sensitive details**
- Add `ConfigError#sensitive` for creating errors with sensitive details.
- Add `ConfigError#redactSensitive` for redacting sensitive details.
- Add `ConfigError#redactedValue` placeholder for redacted details.
- Add …

Add support for hiding and redacting sensitive details

---

docs/src/main/tut/docs/generic-module.md
modules/generic/shared/src/main/scala/ciris/generic/decoders/GenericConfigDecoders.scala
tests/shared/src/test/scala/ciris/generic/decoders/GenericConfigDecodersSpec.scala

Before, the current behaviour of the generic module.
```scala
scala> import ciris._, ciris.generic._
import ciris._
import ciris.generic._
scala> prop[Option[String]]("file.encoding").value
res0: ciris.api.Id[Either[ciris.ConfigError,Option[String]]] = Right(None)
```
After, with the changes in this pull request.
```scala
scala> import ciris._, ciris.generic._
import ciris._
import ciris.generic._
scala> prop[Option[String]]("file.encoding").value
res0: ciris.api.Id[Either[ciris.ConfigError,Option[String]]] = Right(Some(UTF8))
```

Prevent generic decoding for Option

---

.travis.yml
build.sbt
docs/src/main/tut/docs/contributing.md
docs/src/main/tut/index.md
modules/core/shared/src/main/scala/ciris/decoders/MathConfigDecoders.scala

Some reasons for removing Scala 2.10 support:
- interest in Scala 2.10 is low: ~13.6% of total downloads last month were for 2.10 modules,
- a [sbt bug](https://github.com/sbt/sbt/issues/4181) prevents us from using libraries which are not published for Scala 2.10,
- increased maintenance burden, especially with Scala 2.13 coming up,
- only one external module, `ciris-kubernetes`, supports Scala 2.10,
- want to encourage people to move to newer Scala versions.

Remove support for Scala 2.10

---

build.sbt
docs/src/main/tut/docs/basics.md
docs/src/main/tut/docs/logging.md
modules/core/shared/src/main/scala/ciris/Secret.scala
modules/core/shared/src/main/scala/ciris/internal/digest/GeneralDigest.scala
modules/core/shared/src/main/scala/ciris/internal/digest/Pack.scala
modules/core/shared/src/main/scala/ciris/internal/digest/SHA1Digest.scala
modules/core/shared/src/main/scala/ciris/internal/digest/package.scala
tests/jvm/src/test/scala/ciris/SecretJvmSpec.scala
tests/shared/src/test/scala/ciris/ConfigValueSpec.scala
tests/shared/src/test/scala/ciris/SecretSpec.scala
tests/shared/src/test/scala/ciris/cats/api/CirisInstancesForCatsSpec.scala

- Add minified Bouncy Castle SHA1 implementation translated to Scala. We cannot use `java.security.MessageDigest` as it is not yet available on Scala.js or Scala Native.
We can't use the Bouncy Castle Java implementation directly for the same reason.
- Change `Secret#toString` to include short SHA1 hash (first 7 characters) of value.
- Add `Secret#valueShortHash` and `Secret#valueHash` to be able to retrieve hashes.

Include value short hash in Secret#toString

---

build.sbt
docs/src/main/tut/docs/cats-module.md
docs/src/main/tut/docs/logging.md
modules/cats/shared/src/main/scala/ciris/cats/api/CirisInstancesForCats.scala
modules/cats/shared/src/main/scala/ciris/cats/api/CirisInstancesForCatsBinCompat.scala
modules/cats/shared/src/main/scala/ciris/cats/package.scala
modules/core/shared/src/main/scala/ciris/ConfigErrors.scala
tests/shared/src/test/scala/ciris/cats/api/CirisInstancesForCatsSpec.scala

Having a cats Semigroup is quite handy, as it means you can do a bunch of `loadConfig`s for small parts of your configuration and then `parMapN` them together [like this](https://github.com/ovotech/shipit/blob/5ee7d6536c17f83bf5280798d4f66906e6e6db6a/app/Config.scala#L110-L118).

Add a combine method to ConfigErrors

---

modules/core/shared/src/main/scala/ciris/ConfigValue.scala
tests/shared/src/test/scala/ciris/ConfigValueSpec.scala

This is mostly useful when entire `case class`es are loaded from the environment, as it saves you from having to decode as `Option` and use `getOrElse`.
Example, before:
```scala
final case class Config(
a: String,
b: String
)
loadConfig(
env[String]("A").orElse(prop("a")).orNone,
env[String]("B").orElse(prop("b")).orNone
) { (a, b) =>
Config(
a = a getOrElse "a",
b = b getOrElse "b"
)
}
```
and after, with `orValue`.
```scala
loadConfig(
env[String]("A").orElse(prop("a")).orValue("a"),
env[String]("B").orElse(prop("b")).orValue("b")
)(Config.apply)
```

Add ConfigValue#orValue

---

build.sbt
latestVersion.sbt
project/LatestVersion.scala

When checking binary-compatibility against previous releases, check all releases which should be binary-compatible, rather than just the latest release.

Change to check all binary-compatible releases

---

code_of_conduct.md
docs/src/main/tut/index.md
readme.md

Typelevel is [switching to the Scala Code of Conduct](https://typelevel.org/blog/2019/05/01/typelevel-switches-to-scala-code-of-conduct.html), and encourages all member projects to adopt it.

Add Scala Code of Conduct

---

modules/core/src/main/scala/ciris/ConfigValue.scala
modules/core/src/test/scala/ciris/ConfigValueSpec.scala

Consider the following example (`a, b, c, d` are `ConfigValue`s).
```scala
(a, b, c).parTupled.flatMap(... => d).default(e)
```
Assuming `a, b, c` can be loaded (or are defaults), `d` is returned. The default `e` will then be used as long as `d` is missing (or is a default).
Consider the same example but with `parFlatMap`.
```scala
(a, b, c).parTupled.parFlatMap(... => d).default(e)
```
The default `e` will be used as long as all of `a, b, c, d` are missing (or are defaults).
As such, `flatMap` describes two separate configurations, while `parFlatMap` describe a single configuration with dependencies between values.
We call it `parFlatMap` since it's the `flatMap` on `ConfigValue.Par` consistent with its `ap`.
Note `parFlatMap` is not tail-recursive, and cannot be implemented using …

Add ConfigValue#parFlatMap

---

modules/core/src/main/scala/ciris/ConfigValue.scala

I was browsing the new code and I noticed the use of `unsafeRunSync` here didn't appear to be necessary.  
This refactor changes the shuffle from `F ~> IO ~> G` without using `unsafeRuncSync`

Refactor ConfigValue eval and evalMap to not use unsafeRunSync.

---

modules/core/src/test/scala/ciris/ConfigValueSpec.scala

Noticed in community build
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3305/
The syntax was previously too loose.

Remove bad trailing comma in test

---

build.sbt
modules/core/src/main/scala/ciris/ConfigValue.scala
modules/core/src/test/scala/ciris/CirisSpec.scala
modules/core/src/test/scala/ciris/ConfigValueSpec.scala

- Add `ConfigValue.resource` for lifting a `Resource` into a `ConfigValue`.
- Add `ConfigValue#resource` for returning a `Resource` from a `ConfigValue`.

Change ConfigValue to support Resource

---

modules/core/src/main/scala/ciris/ConfigDecoder.scala
modules/core/src/test/scala/ciris/ConfigDecoderSpec.scala

Particularly useful when defining decoders for sensitive types, where the value should never be in error messages.

Add ConfigDecoder#redacted

---

.gitignore
modules/http4s/src/main/scala/ciris/http4s/http4s.scala
modules/http4s/src/test/scala/ciris/http4s/Http4sSpec.scala

Added the support for ip4s Host and Port as config values (+ tests) IP4s is a transitive depndency of Http4s, and those types are required to setup server backends.
I also added some lines to the `.gitignore` to help vscode users contributing.

Add Host and Port ConfigDecoders in the Http4s module

---

build.sbt
modules/core/shared/src/main/scala/ciris/ConfigValue.scala
modules/core/shared/src/test/scala/ciris/ConfigValueSpec.scala

Separates `ConfigValue.async` into `async` and `async_` to mimic cats-effect.
Also updates http4s to 0.23.19.

Update cats-effect to 3.5.0

---

modules/core/shared/src/main/scala/ciris/ConfigValue.scala

Add `ConfigValue.missing(description)` alias for `ConfigValue.missing(ConfigKey(description))`.

Add ConfigValue.missing(String)

---

modules/core/shared/src/main/scala/ciris/ConfigException.scala
modules/core/shared/src/test/scala/ciris/ConfigExceptionSpec.scala
modules/core/shared/src/test/scala/ciris/Generators.scala

Messages in `ConfigException` are now indented after line breaks.
Example before:
```
ciris.ConfigException: configuration loading failed with the following errors.
- Failed to parse file at <path> with charset UTF-8:
// TODO
^
expectation:
* must end the string.
```
Example after:
```
ciris.ConfigException: configuration loading failed with the following errors.
- Failed to parse file at <path> with charset UTF-8:
// TODO
^
expectation:
* must end the string.
```

Change ConfigException to indent messages after line breaks

---

build.sbt
modules/circe-yaml/src/test/scala/ciris/circe/yaml/CirceYamlSpec.scala

Update circe-yaml to 0.15.1

---

build.sbt

Also drops support for Scala 2.12 for ciris-circe-yaml due to circe-yaml no longer being published for Scala 2.12.

Update circe-yaml to 0.16.0

---

modules/core/shared/src/main/scala/ciris/ConfigValue.scala
modules/core/shared/src/test/scala/ciris/ConfigValueSpec.scala

While working on #850, I really felt the lack of an OOTB equivalent to `.flatTap` and `attemptTap` for debugging.
I split this off from #851 as they're only really aligned in the sense that the same issue inspired the PR.

Add taps to ConfigValue

---

docs/src/main/mdoc/configurations.md
modules/core/shared/src/main/scala/ciris/ConfigError.scala
modules/core/shared/src/main/scala/ciris/ConfigValue.scala
modules/core/shared/src/test/scala/ciris/ConfigValueSpec.scala

Adds `alt` as a more permissive alternative to `or` as a possible solution for #850
These helpers will be assumed for the examples:
```scala
val l  = ConfigValue.loaded(ConfigKey("loaded 0", 0))
val l1 = ConfigValue.loaded(ConfigKey("loaded 1", 1))
val mE  = ConfigError.Missing(ConfigKey("missing 0"))
val mE1 = ConfigError.Missing(ConfigKey("missing 0"))
val m  = ConfigValue.failed(mE)
val m1 = ConfigValue.failed(mE0)
val fE  = ConfigError("failed 0")
val f  = ConfigValue.failed(fE)
val d  = ConfigValue.default(2)
val d1 = ConfigValue.default(3)
```
When `a` is a singular value, the behavior of `or` and `alt` are identical:
| `lhs` | `rhs` | `lhs.or(rhs)`            | `lhs.alt(rhs)`     |
| :---- | :---- | :----------------------- | :----------------------- |
| `l`   | `*`   | Loaded: `0` …

Add alt as a more permissive alternative to or
